server {
    listen      443 ssl;
    listen      [::]:443 ssl;

    server_name ${DOMAIN_NAME};  # variable inyectada por docker-compose

    # ── SSL ──────────────────────────────────────────
    ssl_certificate     /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    # Solo TLS 1.2 y 1.3 (subject obligatorio)
    ssl_protocols       TLSv1.2 TLSv1.3;

    # ── WordPress ────────────────────────────────────
    root  /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # Pasa PHP a WordPress (contenedor wordpress:9000)
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass            wordpress:9000;  # nombre del servicio en docker-compose
        fastcgi_index           index.php;
        include                 fastcgi_params;
        fastcgi_param           SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param           PATH_INFO $fastcgi_path_info;
    }
}