[www]

; Usuario bajo el que corre php-fpm
user  = www-data
group = www-data

; Escucha en todas las interfaces del contenedor en el puerto 9000
; NGINX se conectará aquí con fastcgi_pass wordpress:9000
listen = 0.0.0.0:9000

; Gestión dinámica de procesos worker
pm                   = dynamic
pm.max_children      = 5
pm.start_servers     = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3