; /etc/php/7.4/fpm/pool.d/www.conf
; Configuración del pool de php-fpm para WordPress

[www]
; Usuario/grupo bajo el que corren los workers de php-fpm
user = www-data
group = www-data

; ESCUCHA EN PUERTO TCP (no socket unix)
; Nginx se conectará a wordpress:9000 via red Docker
listen = 0.0.0.0:9000

; Cómo gestiona los procesos worker
pm = dynamic

; Máximo de workers en paralelo
pm.max_children = 5

; Workers arrancados al inicio
pm.start_servers = 2

; Mínimo de workers sin peticiones (en espera)
pm.min_spare_servers = 1

; Máximo de workers sin peticiones
pm.max_spare_servers = 3

; Logs de acceso de php-fpm
access.log = /proc/self/fd/2

; Variables de entorno disponibles para PHP
; Necesario para que PHP pueda acceder a $_ENV
clear_env = no
